### start security management
###  login ###
POST {{base_url}}/login
Accept: application/json
Content-Type: application/json

{
  "username":"b.ocine@live.fr",
  "password":"user1"
}
### end security management ###


### create visitor ###
POST {{base_url}}/customers/2/visitors
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email":"test2@gmail.com",
  "password":"delete",
  "roles":
  [
    {
      "id":2
    }
  ]
}

### start visitors management
### visitors list
GET {{base_url}}/customers/2/visitors
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### show visitor
GET {{base_url}}/customers/2/visitors/63
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### update visitor ###
PUT {{base_url}}/customers/2/visitors/62
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "password":"chaglké1",
    "roles":
    [
        {
            "id":2
        }
    ]
}

### delete visitor ###
DELETE {{base_url}}/customers/2/visitors/62
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
### end visitors management


### start admins management
### create admin
POST {{base_url}}/admins
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email":"admin@gmail.com",
  "password":"admin",
  "roles":
  [
    {
      "id":1
    }
  ]
}

### admins list
GET {{base_url}}/admins
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### show admin
GET {{base_url}}/admins/70
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### update admin ###
PUT {{base_url}}/admins/70
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "password":"admin2",
  "roles":
  [
    {
      "id":1
    }
  ]
}

### delete admin
DELETE {{base_url}}/admins/70
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### end admins management


### start customers management
### create customer
POST {{base_url}}/customers
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "company":"allo pièces",
  "code": "2A2562",
  "enabled": 0
}

### customers list
GET {{base_url}}/customers
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### show customer
GET {{base_url}}/customers/15
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### update customer ###
PUT {{base_url}}/customers/15
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "company":"allotoz",
  "code": "2A2562",
  "enabled": 0
}

### delete customer
DELETE {{base_url}}/customers/15
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### end customers management


### start customers management
### create customer
POST {{base_url}}/products
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name":"Iphone 12",
  "description":"votre nouvel iphone est doté d'un système ...",
  "brand":
  {
    "id":5
  },
  "memory":
  {
    "id":3
  },
  "country":
  {
    "id":2
  },
  "user":
  {
    "id":1
  },
  "colors":
  [
    {
      "id":6
    }
  ],
  "images":
  [
    {
      "src":"https://www.frandroid.com/marques/samsung/599043_test-samsung-galaxy-a10"
    },
    {
      "src":"https://www.frandroid.com/marques/samsung/599043_test-samsung-galaxy-a10"
    }
  ]
}

### products list
GET {{base_url}}/products
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### show product
GET {{base_url}}/products/11
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### update product ###
PUT {{base_url}}/products/11
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name":"Iphone 12 modifié",
  "description":"votre nouvel iphone est doté d'un système ...",
  "brand":
  {
    "id":5
  },
  "memory":
  {
    "id":3
  },
  "country":
  {
    "id":2
  },
  "user":
  {
    "id":1
  },
  "colors":
  [
    {
      "id":6
    }
  ],
  "images":
  [
    {
      "src":"https://www.frandroid.com/marques/samsung/599043_test-samsung-galaxy-a10"
    },
    {
      "src":"https://www.frandroid.com/marques/samsung/599043_test-samsung-galaxy-a10"
    }
  ]
}

### delete product
DELETE {{base_url}}/products/11
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### end products management


### start brands management
### create brand
POST {{base_url}}/brands
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Vodafone"
}

### brands list
GET {{base_url}}/brands
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### show brand
GET {{base_url}}/brands/34
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### update brand ###
PUT {{base_url}}/brands/34
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Microsoft"
}

### delete brand
DELETE {{base_url}}/brands/34
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### end brands management


### start colors management
### create color
POST {{base_url}}/colors
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Yellow"
}

### colors list
GET {{base_url}}/colors
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### show color
GET {{base_url}}/colors/14
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### update color ###
PUT {{base_url}}/colors/14
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Red"
}

### delete color
DELETE {{base_url}}/colors/13
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### end colors management


