### start security management
###  login ###
POST {{base_url}}/login
Accept: application/json
Content-Type: application/json

{
  "username":"example@gmail.com",
  "password":"admin"
}
### end security management ###


### create visitor ###
POST {{base_url}}/customers/30/visitors
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email":"hocine@gmail.com",
  "password":"delete",
  "roles":
  [
    {
      "id":2
    }
  ]
}

### start visitors management
### visitors list
GET {{base_url}}/customers/30/visitors
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### show visitor
GET {{base_url}}/customers/30/visitors/104
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### update visitor ###
PUT {{base_url}}/customers/30/visitors/104
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email":"te@gmail.com",
  "password":"user1",
    "roles":
    [
        {
            "id":2
        }
    ]
}

### delete visitor ###
DELETE {{base_url}}/customers/30/visitors/102
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}
### end visitors management


### start admins management
### create admin
POST {{base_url}}/admins
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email":"admin5@gmail.com",
  "password":"admin",
  "roles":
  [
    {
      "id":1
    }
  ]
}

### admins list
GET {{base_url}}/admins
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### show admin
GET {{base_url}}/admins/106
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### update admin ###
PUT {{base_url}}/admins/10
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email":"admin@gmail.com",
  "password":"adm1554",
  "roles":
  [
    {
      "id":1
    }
  ]
}

### delete admin
DELETE {{base_url}}/admins/106
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### end admins management


### start customers management
### create customer
POST {{base_url}}/customers
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "company":"allo pièces",
  "enabled": 0
}

### customers list
GET {{base_url}}/customers
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### show customer
GET {{base_url}}/customers/31
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### update customer ###
PUT {{base_url}}/customers/32
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "company":"allo pièces",
  "code": "2A2562",
  "enabled": 0
}

### delete customer
DELETE {{base_url}}/customers/31
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### end customers management


### start products management
### create product
POST {{base_url}}/products
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name":"Iphone 11",
  "description":"votre nouvel iphone est doté d'un système ...",
  "brand":
  {
    "id":5
  },
  "memory":
  {
    "id":3
  },
  "country":
  {
    "id":2
  },
  "user":
  {
    "id":1
  },
  "colors":
  [
    {
      "id":6
    }
  ],
  "images":
  [
    {
      "src":"https://www.frandroid.com/marques/samsung/599043_test-samsung-galaxy-a10"
    },
    {
      "src":"https://www.frandroid.com/marques/samsung/599043_test-samsung-galaxy-a10"
    }
  ]
}

### products list
GET {{base_url}}/products
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### show product
GET {{base_url}}/products/17
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### update product ###
PUT {{base_url}}/products/16
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name":"Iphone 10",
  "description":"votre nouvel iphone est doté d'un système ...",
  "brand":
  {
    "id":5
  },
  "memory":
  {
    "id":3
  },
  "country":
  {
    "id":2
  },
  "user":
  {
    "id":1
  },
  "colors":
  [
    {
      "id":6
    }
  ],
  "images":
  [
    {
      "src":"https://www.frandroid.com/marques/samsung/599043_test-samsung-galaxy-a10"
    },
    {
      "src":"https://www.frandroid.com/marques/samsung/599043_test-samsung-galaxy-a10"
    }
  ]
}

### delete product
DELETE {{base_url}}/products/16
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### end products management


### start brands management
### create brand
POST {{base_url}}/brands
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Vodafone"
}

### brands list
GET {{base_url}}/brands
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### show brand
GET {{base_url}}/brands/4
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### update brand ###
PUT {{base_url}}/brands/4
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Oppo"
}

### delete brand
DELETE {{base_url}}/brands/43
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### end brands management


### start colors management
### create color
POST {{base_url}}/colors
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "rouge"
}

### colors list
GET {{base_url}}/colors
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### show color
GET {{base_url}}/colors/16
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### update color ###
PUT {{base_url}}/colors/16
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "rouge"
}

### delete color
DELETE {{base_url}}/colors/16
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### end colors management


### start countries management
### create country
POST {{base_url}}/countries
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "usa"
}

### countries list
GET {{base_url}}/countries
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### show country
GET {{base_url}}/countries/6
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### update country ###
PUT {{base_url}}/countries/11
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Allemagne"
}

### delete country
DELETE {{base_url}}/countries/1174
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### end cuntries management


### start memories management
### create memory
POST {{base_url}}/memories
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "memoryCapacity": "256Go"
}

### memories list
GET {{base_url}}/memories
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### show memory
GET {{base_url}}/memories/100
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### update memory ###
PUT {{base_url}}/memories/3
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "memoryCapacity": "64Go"
}

### delete memory
DELETE {{base_url}}/memories/10
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

### end memories management


